kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephrbd-sc
provisioner: ceph.com/rbd
parameters:
  monitors: 10.164.0.97:6789,10.164.0.100:6789,10.164.0.101:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: kubernetes_pool
  userId: admin
  userSecretName: ceph-secret-user
  userSecretNamespace: default
  fsType: xfs
  imageFormat: "2"
  imageFeatures: "layering"
