apiVersion: v1
kind: Service
metadata:
  name: redis-lmx-service
  labels:
    app: redis-lmx
spec:
  ports:
  - name: redis-lmx-port
    port: 6379
  clusterIP: None
  selector:
    app: redis-lmx
    appCluster: redis-lmx-cluster
