apiVersion: v1
kind: Service
metadata:
  name: cachecloud-mysql
  labels:
    app: cachecloud
spec:
  ports:
    - port: 3306
  selector:
    app: cachecloud
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cachecloud-mysql-pvc
  labels:
    app: cachecloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephrbd-sc
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cachecloud-mysql
  labels:
    app: cachecloud
spec:
  selector:
    matchLabels:
      app: cachecloud
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cachecloud
        tier: mysql
    spec:
      containers:
      - image: private.registry.com/library/mysql:5.7
        name: cachecloud-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: cachecloudmysql
        volumeMounts:
        - name: cachecloud-mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: cachecloud-mysql-storage
        persistentVolumeClaim:
          claimName: cachecloud-mysql-pvc
